### ISSUE TITLE
Grey screen after splash screen

### ISSUE THREAD

**Issue by SSebigo** [febryardiansyah/animku#1]
As the title suggests, I get a grey screen after the splash screen.

Device: Samsung S9+
Android: 10

**Comment by SSebigo** [comment]
If I had to guess, I'd say that a value is not initialized:

1. during the transition from splash screen to home screen
2. when it's used inside home screen

resulting in Flutter/Dart throwing an Exception.

**Comment by febryardiansyah** [comment]
thank you for testing my app, i was also checking this app and got same issue which is grey screen after splashscreen. I'll check it now 😄

**Comment by febryardiansyah** [comment]
i fix this, the problem was coming from bottomnavbar. i didn't initialize currentSeasonIndex properly which is current month is june not jun 🤣
https://github.com/febryardiansyah/animku/blob/master/lib/components/bottom_navbar.dart
