### ISSUE TITLE
Bad practice: used of timer in splash screen

### ISSUE THREAD

**Issue by SSebigo** [febryardiansyah/animku#2]
If you have no data to load during the splash screen then just let it transition at normal pace (e.g. as soon as it appears) or don'tshow it at all.

In the other hand, if you load data during the splash screen, use an await or something and transition as soon as the data are loaded.

But delaying for the sake of delaying is bad practice overall.

**Comment by febryardiansyah** [comment]
Wow, thanks for your suggestion. i just new in flutter and this is really help me a lot 😆.
if you want, u can fix that splashscreen and pull request in this repo. that will be really helpful😃

**Comment by SSebigo** [comment]
I'll do it and since I'm at it I'll try to fix some syntax issues just for future contributors.
And try to use strictly English naming convention (class, methods, variables, etc).
